//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4NH_HAO_Coffee_Shop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfor
    {
        public int IdNumber { get; set; }
        public string ItemId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Item Item { get; set; }
    }
}
