//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4NH_HAO_Coffee_Shop.Model
{
    using _4NH_HAO_Coffee_Shop.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Item : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.BillInfors = new HashSet<BillInfor>();
        }

        private string _Id;
        public string Id
        {
            get { return _Id; }
            set { _Id = value; OnPropertyChanged(); }
        }
        private string _DisplayName;
        public string DisplayName
        {
            get { return _DisplayName; }
            set { _DisplayName = value; OnPropertyChanged(); }
        }
        private int _UnitId;
        public int UnitId
        {
            get { return _UnitId; }
            set { _UnitId = value; OnPropertyChanged(); }
        }
        private int _CategoryId;
        public int CategoryId
        {
            get { return _CategoryId; }
            set { _CategoryId = value; OnPropertyChanged(); }
        }
        private int _Price;
        public int Price
        {
            get { return _Price; }
            set { _Price = value; OnPropertyChanged(); }
        }
        private string _ImageURL;
        public string ImageURL
        {
            get { return _ImageURL; }
            set { _ImageURL = value; OnPropertyChanged(); }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfor> BillInfors { get; set; }
        public virtual Category Category { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
